# -*- coding: utf-8 -*-
"""unemployment analysis with python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cJiG6XffCOAL1GNyBhPyikvT9Vj0LMXy
"""

#UNEMPLOYMENT ANALAYSIS USING PYTHON



import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

data  = pd.read_csv("https://raw.githubusercontent.com/amankharwal/Website-data/master/unemployment.csv")
print(data.head())

data.info

print(data.describe)

# see if the data contains any null values
print(data.isnull().sum())

# RENAMING ALL COLOUMS
data.columns =["states","Date","Frequency","Estimated Unemployment Rate","Estimated Employed","Estimated Labour Participation Rate","Region","Longitude","Latitude" ]

print(data)

#look at the correlation b/w the features of this dataset
plt.style.use("seaborn-whitegrid")
plt.figure(figsize=(12,10))
sns.heatmap(data.corr())
plt.show()

#look at the estimated number of employees according to different regoins of india
data.columns =["states","Date","Frequency","Estimated Unemployment Rate","Estimated Employed","Estimated Labour Participation Rate","Region","Longitude","Latitude"]
plt.title("Indian unemployment")
sns.histplot(x="Estimated Employed",hue="Region",data=data)
plt.show()

#see the unemployment rate according to different region of india.
plt.figure(figsize=(12,10))
plt.title("Indian unemployment")
sns.histplot(x="Estimated Unemployment Rate",hue="Region",data=data)
plt.show()

unemployment = data[["states","Region","Estimated Unemployment Rate"]]
figure = px.sunburst(unemployment,path=["Region","states"],values="Estimated Unemployment Rate",width=700,height=700,color_continuous_scale="RdY1Gn",
                     title="Unemployment Rate in India")
figure.show()